print('xxxxxxxxxxxxxx')
                    # print('Game: '+str(j))
                    # print('Move: '+str(i))
                    # print('History: '+str(game_history[k]))
                    # print('Position: '+str(position))
                    # print('Unique ID: ' +str(unique_history[k]))